### PR TITLE
Add istanbul-merge #74

### LINKED ISSUE #74: Coverage for monorepo
## Description

We can get coverage of some packages and now we send only coverage of `vm` to [coveralls](https://coveralls.io/github/cryptoeconomicslab/plasma-chamber).
Can we summarize coverage of all packages?

## References

- https://coveralls.io/github/cryptoeconomicslab/plasma-chamber
or you can use
https://codecov.io/gh/cryptoeconomicslab/plasma-chamber

### PR DESCRIPTION
**Pull request by syuhei176**
## Task List

* [x] core
* [x] wallet
* [ ] contract
* [x] childchain

Close #74 

patch

### CODE REVIEW

**Comment by syuhei176** [comment]
core+wallet+child chain were finished. try solidity-coverage for vyper.

**Comment by syuhei176** [comment]
hmm can't succeed to run specs with solidity-coverage.
omit coverage of vyper in this PR.

**Comment by shogochiai** [comment]
@syuhei176 it seems `istanbul` isn't maintained anymore, and `nyc` is actively maintained by the same team. And `nyc` has monorepo merger by default 

https://github.com/istanbuljs/nyc#using-include-and-exclude-arrays

How do you see that?

**Comment by syuhei176** [comment]
Thanks I'll try nyc.

**Comment by syuhei176** [comment]
> https://github.com/istanbuljs/nyc#using-include-and-exclude-arrays

Maybe this is not for monorepo, just example of `exclude`.

**Comment by syuhei176** [comment]
I found merge command. but no document.
https://github.com/istanbuljs/nyc/blob/c21346911f7772ba282a003beec05bda41dbc766/bin/nyc.js#L22

**Comment by syuhei176** [comment]
I was able to use `nyc merge`.
output of merge is son.
But coveralls require lcov.
https://github.com/istanbuljs/nyc/blob/master/docs/setup-coveralls.md

**Comment by syuhei176** [comment]
continue in https://github.com/cryptoeconomicslab/plasma-chamber/pull/314

**Pull request closed without merging**
