### PR TITLE
Optimizing root chain contract

### PR DESCRIPTION
**Pull request by syuhei176**
## Description

It need refactoring since it was exceeded contract size limit.

### CODE REVIEW

**Comment by shogochiai** [comment]
screen shot 2018-12-14 at 14 53 04

Gimme feedback. Is this appended statement correct?

@syuhei176

**Comment by shogochiai** [comment]
I understood these design change is

1. spendChallenge(=challengeAfter) is the same as "plasma cash simple spec"
2. doubleSpendChallenge(=challengeBetween) and invalidHistoryChallenge(=challengeBefore) has been merged as "Challenge Game". But the beginning function of challenge game is still named "challengeBefore"
3. Double Spend handling(=the role of "challengeBetween") is involved into "respondParent", and so *challenge game doesn't require 2 Tx from the beginning*. <== This is the cost cutting point.

**Comment by shogochiai** [comment]
Will it be added to this PR regarding the spec-should-be-added?

**Comment by syuhei176** [comment]
@shogochiai I checked test run. with https://github.com/cryptoeconomicslab/plasma-chamber/pull/141/commits/a9527a7019e4a37a251b5e8e77adc40b4b406623

We should update the package version after merging this PR and update plasma-wallet repo.

We'll do these step.
1. merge this PR.
2. update package(`lerna publish`)
3. modify plasma-wallet and poker

**Pull request merged**
