### PR TITLE
Fix exit procedure

### LINKED ISSUE #142: User can respond by any input
## Description

The user can respond by any input of exiting transaction.
In the current implementation, only 0 index of inputs is stored.
https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/packages/chamber-rootchain/contracts/RootChain.sol#L240

### PR DESCRIPTION
**Pull request by syuhei176**
## Description

Fix exit process

- exiting tx has multiple inputs
- the challenger can challenge respond tx with **double spent**

Closes #142 

need double check

### CODE REVIEW

**Comment by syuhei176** [comment]
note: RespondParent and ChallengeBetween in challenge game are special functions for withholding scenario.

### Scenario

tx1: Alice receives coin A from someone.
tx2: invalid transaction
tx3: Alice transfer coin A to Bob.

tx1.blkNum < tkx2.blkNum < tx3.blkNum

operator submit invalid transaction before tx3.

1. Bob exit with tx3
2. Operator challenge with tx2
3. Bob respondParent with tx1(tx1 is the real parent of tx3)
4. The operator cannot do `challengeBetween` since tx2 is not a child of tx1.

**Comment by shogochiai** [comment]
Finally I catched up that this discussion is coming from this one
https://scrapbox.io/cryptoeconimicslab/Optimize_Exit_Process

**Comment by shogochiai** [comment]
- [ ] All possible malicious exits are involved in test cases?
    - [ ] Exit by non-block-included, spent, or withdrawn UTXO
    - [ ] Exit by a Tx which has malformed Tx in its history
    - [ ] Exit by a Tx which has double spending Tx pair
    - 🐒 Any other possible "malicious" Tx?
        - Can we get efficient logical framework to narrow down we've been able to check all malicious exit MECE
- [ ] Do those collectively can be challenged?

**Comment by shogochiai** [comment]
For sagely merging this PR, please answer

1. Is Plasma Chamber currently assigning Plasma Prime Txs? I would like to see explicit list of possible "transaction type". 
- Transfer(Split&Merge), Swap, Variety of Multisigs are maximally possible now I think. Which is assumed to be in this PR?

2. Are these Txs intruduced any malicious(fund damaging) exit vector?
- Is the 1 arg challenge for mitigating attack vector introduced by Primw? Or just an optimization of gas?

3. If there is, are there test cases that assert all exits are collectively challenged?

**Comment by syuhei176** [comment]
For sagely merging this PR, please answer

> Is Plasma Chamber currently assigning Plasma Prime Txs? I would like to see explicit list of possible "transaction type".

current implemented transaction is here.
https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/packages/chamber-rootchain/contracts/TxVerification.sol#L18
https://github.com/cryptoeconomicslab/plasma-chamber/blob/master/packages/chamber-rootchain/contracts/MultisigGame.sol#L24

> Transfer(Split&Merge), Swap, Variety of Multisigs are maximally possible now I think. Which is assumed to be in this PR?

 force include is in this PR. https://github.com/cryptoeconomicslab/plasma-chamber/issues/127

> Are these Txs intruduced any malicious(fund damaging) exit vector?

can you elaborate this? 

Is the 1 arg challenge for mitigating attack vector introduced by Primw? Or just an optimization of gas?

multi player game. but we can ignore this.

> If there is, are there test cases that assert all exits are collectively challenged?

We have no application like multi player commit&reveal, we can't test.
we can ignore this case.

**Comment by syuhei176** [comment]
updated picture, add 'respond by'

**Pull request closed without merging**
